name: flutter_pixelmatching
description: Module to perform feature matching using OpenCV
version: 1.0.0
homepage: https://github.com/lowapple/flutter_pixelmatching

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  camera: ^0.10.3+2
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  image: ^4.0.15
  image_picker: ^0.8.7+1

dev_dependencies:
  ffigen: ^7.2.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true

ffigen:
  description: 'FFI bindings for OpenCV'
  output: './lib/src/pixelmatching_bindings.dart'
  name: 'PixelMatchingBindings'
  compiler-opts:
    - '-I./include/'
  headers:
    entry-points:
      - './src/PixelMatching.h'
      - './src/YuvToJpeg.h'