name: Workflow for Codecov Action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '3.7.0'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Install coverage tools
        run: flutter pub global activate coverage
      - name: format coverage
        run: $HOME/.pub-cache/bin/format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.lcov
          verbose: true
